#!/bin/sh

function update {
    data=$(curl -s -X GET -H 'Content-Type: application/json' 'https://www.dolarsi.com/api/api.php?type=dolar')
    exec echo $data | jq > /tmp/usdtoars.txt
}

function gettemp {
    data=$(cat /tmp/usdtoars.txt)
}

function autoupdate {
    if [ -a /tmp/usdtoars.txt ]
    then
        current_date=$(date +'%s')
        file_date=$(stat -c %Y /tmp/usdtoars.txt)
        diff=$(expr $current_date - $file_date)
        diff=$(expr $diff / 60)

        if [ $diff -ge 10 ]
        then
            update
        else
            gettemp
        fi
    else
        update
    fi
}

function useofficial {
    ars='0'
    exchange=$(echo $data | jq '.[0].casa.venta')
}

function useblue {
    ars='0'
    exchange=$(echo $data | jq '.[1].casa.venta')
}

function usears {
    ars='1'
}

function showexchange {
    o=$(echo $exchange | grep -o '[0-9,]\+[1-9]')
    echo $o
}

function showhelp {
    echo "Usage: usdtoars <option> <value>"
    echo "-a,--autoupdate        Autoupdate"
    echo "-u,--update            Force Update"
    echo "--get-official         Show official exchange value"
    echo "--get-blue             Show blue exchange value"
    echo "--use-official         Use official value to convert"
    echo "--use-blue             Use blue value to convert"
    echo "--use-ars              Convert from ars to usd official"
    echo "--use-ars-blue         Convert from ars to usd blue"
}

function convert {
    _exchange=$(echo $exchange | grep -o '[0-9]\+' | head -n1)
    if [ $ars = '1' ]
    then
        _calc=$(($value / $_exchange))
    else
        _calc=$(($_exchange * $value))
    fi
    echo $_calc
}

case $1 in
    "-a" | "--autoupdate")
        autoupdate
        ;;
    "-u" | "--update")
        update
        ;;
    "--get-official")
        autoupdate
        useofficial
        showexchange
        ;;
    "--get-blue")
        autoupdate
        useblue
        showexchange
        ;;
    "--use-official")
        value=$2
        autoupdate
        useofficial
        convert
        ;;
    "--use-blue")
        value=$2
        autoupdate
        useblue
        convert
        ;;
    "--use-ars")
        value=$2
        autoupdate
        useofficial
        usears
        convert
        ;;
    "--use-ars-blue")
        value=$2
        autoupdate
        useblue
        usears
        convert
        ;;
    "" | "-h" | "--help")
        showhelp
        ;;
esac
